# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-27 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=5, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
