# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-27 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0003_auto_20170328_0049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tiket',
            new_name='Ticket',
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-project', 'summary'], 'verbose_name': '\u0437\u0430\u0434\u0430\u0447\u0430', 'verbose_name_plural': '\u0437\u0430\u0434\u0430\u0447\u0438'},
        ),
    ]
