# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0005_auto_20170416_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='original_name',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
        migrations.AddField(
            model_name='movie',
            name='actor_1_facebook_likes',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='actor_1_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='actor_2_facebook_likes',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='actor_2_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='actor_3_facebook_likes',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='actor_3_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='aspect_ratio',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='budget',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast_total_facebook_likes',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='color',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='content_rating',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='director_facebook_likes',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='director_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='facenumber_in_poster',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='gross',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_score',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_facebook_likes',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_imdb_link',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_title',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='num_critic_for_reviews',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='num_user_for_reviews',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='num_voted_users',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='plot_keywords',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_year',
            field=models.CharField(default='', max_length=256),
        ),
    ]
